/**
 * Append Opus-curated music gossip questions to data/quiz-gossip-bank.json.
 * Verified pop culture facts about music artist drama, scandals, beefs, and breakups.
 *
 * Usage: node scripts/append-gossip.js
 */

import { readFileSync, writeFileSync } from 'node:fs';
import crypto from 'node:crypto';

const PATH = 'data/quiz-gossip-bank.json';

const QUESTIONS = [
  // ─── BEEFS & FEUDS ────────────────────────────────────
  {
    questionText: "Which two rappers had the legendary 2024 beef that produced 'Not Like Us' as the year's biggest diss track?",
    correctAnswer: "Kendrick Lamar vs. Drake",
    options: ["Kendrick Lamar vs. Drake", "Eminem vs. MGK", "Pusha T vs. Drake", "Nas vs. Jay-Z"],
    artistName: "Kendrick Lamar",
    funFact: "'Not Like Us' won 5 Grammys including Record AND Song of the Year — first diss track ever to win.",
    backgroundSongName: "Not Like Us",
    backgroundArtist: "Kendrick Lamar",
    difficulty: "easy",
    category: "beef",
    gossipDate: "2024",
  },
  {
    questionText: "What infamous 1995-1997 East Coast vs. West Coast hip-hop feud ended tragically?",
    correctAnswer: "Tupac vs. Notorious B.I.G.",
    options: ["Tupac vs. Notorious B.I.G.", "Jay-Z vs. Nas", "Eminem vs. Ja Rule", "50 Cent vs. The Game"],
    artistName: "Tupac Shakur",
    funFact: "Both rappers were murdered in drive-by shootings — Tupac in 1996, Biggie in 1997. Both cases remain unsolved.",
    backgroundSongName: "California Love",
    backgroundArtist: "2Pac",
    difficulty: "medium",
    category: "feud",
  },
  {
    questionText: "Which two pop stars had the famous 2000s feud that started with a stolen MTV Moonman?",
    correctAnswer: "Kanye West & Taylor Swift",
    options: ["Kanye West & Taylor Swift", "Beyoncé & Rihanna", "Britney & Christina", "Katy Perry & Taylor Swift"],
    artistName: "Kanye West",
    funFact: "Kanye interrupted Taylor's 2009 VMA acceptance speech: 'Imma let you finish but Beyoncé had one of the best videos of all time.'",
    backgroundSongName: "Famous",
    backgroundArtist: "Kanye West",
    difficulty: "easy",
    category: "feud",
  },
  {
    questionText: "Which two pop stars had a famous 2010s feud over backup dancers, immortalized in 'Bad Blood'?",
    correctAnswer: "Taylor Swift vs. Katy Perry",
    options: ["Taylor Swift vs. Katy Perry", "Britney vs. Christina", "Mariah vs. Whitney", "Madonna vs. Cher"],
    artistName: "Taylor Swift",
    funFact: "They made up in 2018 — Katy sent Taylor a literal olive branch with a handwritten note.",
    backgroundSongName: "Bad Blood",
    backgroundArtist: "Taylor Swift",
    difficulty: "easy",
    category: "feud",
  },
  {
    questionText: "Which Oasis brothers had decades of public feuding before reuniting in 2025?",
    correctAnswer: "Liam & Noel Gallagher",
    options: ["Liam & Noel Gallagher", "Tom & Will Fletcher", "Robin & Maurice Gibb", "Angus & Malcolm Young"],
    artistName: "Oasis",
    funFact: "Oasis announced their 2025 reunion tour after 16 years of public feuding — fans called it the music event of the decade.",
    backgroundSongName: "Wonderwall",
    backgroundArtist: "Oasis",
    difficulty: "easy",
    category: "feud",
    gossipDate: "2025",
  },

  // ─── BREAKUPS & DIVORCES ──────────────────────────────
  {
    questionText: "Which iconic couple's bitter 1996 divorce inspired Adele's '21' album?",
    correctAnswer: "Inspired by her own breakup, not theirs",
    options: [
      "Inspired by her own breakup, not theirs",
      "Sonny and Cher",
      "Whitney Houston & Bobby Brown",
      "Madonna & Sean Penn",
    ],
    artistName: "Adele",
    funFact: "Adele's '21' was inspired by her own breakup with Alex Sturrock — the album sold 31 million copies worldwide.",
    backgroundSongName: "Someone Like You",
    backgroundArtist: "Adele",
    difficulty: "hard",
    category: "breakup",
  },
  {
    questionText: "Which couple's 2016 split inspired Beyoncé's 'Lemonade' album about infidelity?",
    correctAnswer: "Beyoncé & Jay-Z",
    options: ["Beyoncé & Jay-Z", "Rihanna & Chris Brown", "Mariah & Nick Cannon", "Britney & Justin"],
    artistName: "Beyoncé",
    funFact: "The album referenced 'Becky with the good hair' — the internet has never stopped speculating about her identity.",
    backgroundSongName: "Sorry",
    backgroundArtist: "Beyoncé",
    difficulty: "medium",
    category: "infidelity",
  },
  {
    questionText: "Which '90s pop power couple's breakup inspired both 'Cry Me a River' and 'Everytime'?",
    correctAnswer: "Justin Timberlake & Britney Spears",
    options: [
      "Justin Timberlake & Britney Spears",
      "Mariah & Tommy Mottola",
      "Whitney & Bobby",
      "Madonna & Guy Ritchie",
    ],
    artistName: "Justin Timberlake",
    funFact: "Justin's 'Cry Me a River' featured a Britney lookalike in the music video, fueling the breakup drama for years.",
    backgroundSongName: "Cry Me a River",
    backgroundArtist: "Justin Timberlake",
    difficulty: "medium",
    category: "breakup",
  },
  {
    questionText: "Which Fleetwood Mac album was famously written during the band members' multiple internal breakups?",
    correctAnswer: "Rumours",
    options: ["Rumours", "Tusk", "Mirage", "Tango in the Night"],
    artistName: "Fleetwood Mac",
    funFact: "All five band members were going through breakups during recording — Stevie & Lindsey, John & Christine, and Mick's marriage all crumbled.",
    backgroundSongName: "Go Your Own Way",
    backgroundArtist: "Fleetwood Mac",
    difficulty: "easy",
    category: "breakup",
  },

  // ─── SCANDALS ─────────────────────────────────────────
  {
    questionText: "Which Britney Spears scandal kept her under court-ordered conservatorship for 13 years?",
    correctAnswer: "Her 2007 mental health crisis",
    options: [
      "Her 2007 mental health crisis",
      "Her Vegas residency",
      "Her marriage to Kevin Federline",
      "Her tax issues",
    ],
    artistName: "Britney Spears",
    funFact: "The #FreeBritney movement helped end her conservatorship in November 2021 after 13 years.",
    backgroundSongName: "Toxic",
    backgroundArtist: "Britney Spears",
    difficulty: "medium",
    category: "scandal",
  },
  {
    questionText: "Which 2020 documentary exposed the abuse allegations against Michael Jackson by James Safechuck and Wade Robson?",
    correctAnswer: "Leaving Neverland",
    options: ["Leaving Neverland", "Surviving R. Kelly", "Britney vs. Spears", "The Rise of Skywalker"],
    artistName: "Michael Jackson",
    funFact: "The HBO documentary won Emmys but was met with fierce backlash from Jackson's estate.",
    backgroundSongName: "Billie Jean",
    backgroundArtist: "Michael Jackson",
    difficulty: "medium",
    category: "scandal",
  },
  {
    questionText: "Which R&B singer was convicted in 2021 on racketeering and sex trafficking charges?",
    correctAnswer: "R. Kelly",
    options: ["R. Kelly", "Chris Brown", "Trey Songz", "Akon"],
    artistName: "R. Kelly",
    funFact: "R. Kelly was sentenced to 30 years in federal prison after decades of allegations finally caught up to him.",
    backgroundSongName: "I Believe I Can Fly",
    backgroundArtist: "R. Kelly",
    difficulty: "easy",
    category: "scandal",
  },
  {
    questionText: "Which famous music producer was accused in the 2022 documentary 'P. Diddy: The Making of a Bad Boy'?",
    correctAnswer: "Sean 'Diddy' Combs",
    options: ["Sean 'Diddy' Combs", "Russell Simmons", "Dr. Dre", "Lyor Cohen"],
    artistName: "Diddy",
    funFact: "Diddy was arrested in September 2024 on federal charges including racketeering and sex trafficking.",
    backgroundSongName: "I'll Be Missing You",
    backgroundArtist: "Puff Daddy",
    difficulty: "medium",
    category: "scandal",
    gossipDate: "2024",
  },
  {
    questionText: "Which boy band member shocked fans by coming out as gay in 1998?",
    correctAnswer: "Lance Bass (NSYNC)",
    options: ["Lance Bass (NSYNC)", "AJ McLean (Backstreet Boys)", "Justin Timberlake", "Joey Fatone"],
    artistName: "Lance Bass",
    funFact: "Bass actually came out in 2006, not 1998 — but his coming out was a landmark moment for boy band fans.",
    backgroundSongName: "Bye Bye Bye",
    backgroundArtist: "NSYNC",
    difficulty: "hard",
    category: "scandal",
  },

  // ─── DRAMA & DRAMA ────────────────────────────────────
  {
    questionText: "What famously happened at the 2009 VMAs that became the most-quoted Kanye moment of all time?",
    correctAnswer: "He grabbed Taylor Swift's mic mid-speech",
    options: [
      "He grabbed Taylor Swift's mic mid-speech",
      "He proposed to Kim Kardashian on stage",
      "He fell off the stage",
      "He attacked a photographer",
    ],
    artistName: "Kanye West",
    funFact: "President Obama later called Kanye a 'jackass' for the incident in a leaked off-the-record comment.",
    backgroundSongName: "Heartless",
    backgroundArtist: "Kanye West",
    difficulty: "easy",
    category: "drama",
  },
  {
    questionText: "Which singer slapped his actress wife at the 2022 Oscars during a Chris Rock joke?",
    correctAnswer: "He's not a singer — Will Smith slapped Chris Rock",
    options: [
      "He's not a singer — Will Smith slapped Chris Rock",
      "Justin Timberlake",
      "Diddy",
      "Kanye West",
    ],
    artistName: "Will Smith",
    funFact: "Will Smith resigned from the Academy and was banned from Oscars events for 10 years.",
    backgroundSongName: "Gettin' Jiggy Wit It",
    backgroundArtist: "Will Smith",
    difficulty: "easy",
    category: "drama",
  },
  {
    questionText: "Which drummer famously bit the head off a live bat thinking it was a rubber prop in 1982?",
    correctAnswer: "Ozzy Osbourne (vocalist, not drummer)",
    options: [
      "Ozzy Osbourne (vocalist, not drummer)",
      "Tommy Lee",
      "Dave Grohl",
      "Lars Ulrich",
    ],
    artistName: "Ozzy Osbourne",
    funFact: "Ozzy had to get rabies shots after the incident in Des Moines, Iowa.",
    backgroundSongName: "Crazy Train",
    backgroundArtist: "Ozzy Osbourne",
    difficulty: "easy",
    category: "drama",
  },
  {
    questionText: "Which 1989 Madonna song's video had her burning crosses, prompting Pepsi to cancel a $5 million sponsorship?",
    correctAnswer: "Like a Prayer",
    options: ["Like a Prayer", "Material Girl", "Express Yourself", "Vogue"],
    artistName: "Madonna",
    funFact: "Pepsi had paid Madonna $5 million for the deal but pulled out after Catholic groups protested.",
    backgroundSongName: "Like a Prayer",
    backgroundArtist: "Madonna",
    difficulty: "medium",
    category: "drama",
  },
  {
    questionText: "Which 1969 free concert ended in tragedy when Hells Angels security killed an audience member?",
    correctAnswer: "Altamont (Rolling Stones)",
    options: ["Altamont (Rolling Stones)", "Woodstock", "Isle of Wight", "Monterey Pop"],
    artistName: "The Rolling Stones",
    funFact: "Altamont is often called 'the day the 60s died' — captured in the documentary 'Gimme Shelter'.",
    backgroundSongName: "Sympathy for the Devil",
    backgroundArtist: "The Rolling Stones",
    difficulty: "hard",
    category: "drama",
  },

  // ─── DEATHS & TRAGEDIES ───────────────────────────────
  {
    questionText: "Which 27-year-old Nirvana frontman died in April 1994, joining the '27 Club'?",
    correctAnswer: "Kurt Cobain",
    options: ["Kurt Cobain", "Layne Staley", "Chris Cornell", "Scott Weiland"],
    artistName: "Kurt Cobain",
    funFact: "Cobain joined the 27 Club along with Jimi Hendrix, Janis Joplin, Jim Morrison, and Brian Jones — all dead at 27.",
    backgroundSongName: "Smells Like Teen Spirit",
    backgroundArtist: "Nirvana",
    difficulty: "easy",
    category: "tragedy",
  },
  {
    questionText: "Which singer died at age 27 in 2011 after years of public substance abuse struggles?",
    correctAnswer: "Amy Winehouse",
    options: ["Amy Winehouse", "Adele", "Pink", "Duffy"],
    artistName: "Amy Winehouse",
    funFact: "Amy famously sang 'They tried to make me go to rehab, I said no, no, no' — and refused to go.",
    backgroundSongName: "Rehab",
    backgroundArtist: "Amy Winehouse",
    difficulty: "easy",
    category: "tragedy",
  },
  {
    questionText: "Which legendary Queen frontman died from AIDS-related complications in 1991, just one day after publicly confirming his diagnosis?",
    correctAnswer: "Freddie Mercury",
    options: ["Freddie Mercury", "Michael Hutchence", "George Michael", "David Bowie"],
    artistName: "Freddie Mercury",
    funFact: "Mercury kept his diagnosis private for years and only confirmed it the day before his death.",
    backgroundSongName: "Bohemian Rhapsody",
    backgroundArtist: "Queen",
    difficulty: "easy",
    category: "tragedy",
  },
  {
    questionText: "Which pop superstar died from cardiac arrest in his Los Angeles home in June 2009?",
    correctAnswer: "Michael Jackson",
    options: ["Michael Jackson", "Prince", "Whitney Houston", "George Michael"],
    artistName: "Michael Jackson",
    funFact: "His doctor Conrad Murray was convicted of involuntary manslaughter for administering propofol.",
    backgroundSongName: "Thriller",
    backgroundArtist: "Michael Jackson",
    difficulty: "easy",
    category: "tragedy",
  },
  {
    questionText: "Which Whitney Houston hit was on the radio when she died in a Beverly Hills hotel bathtub in 2012?",
    correctAnswer: "I Will Always Love You",
    options: ["I Will Always Love You", "I Wanna Dance with Somebody", "How Will I Know", "Saving All My Love"],
    artistName: "Whitney Houston",
    funFact: "She drowned in the bathtub of the Beverly Hilton, where she was preparing for a pre-Grammy party.",
    backgroundSongName: "I Will Always Love You",
    backgroundArtist: "Whitney Houston",
    difficulty: "medium",
    category: "tragedy",
  },
  {
    questionText: "Which rock legend died in his Minnesota home from an accidental fentanyl overdose in 2016?",
    correctAnswer: "Prince",
    options: ["Prince", "David Bowie", "Tom Petty", "Eddie Van Halen"],
    artistName: "Prince",
    funFact: "Prince was found unresponsive in an elevator at his Paisley Park estate on April 21, 2016.",
    backgroundSongName: "Purple Rain",
    backgroundArtist: "Prince",
    difficulty: "easy",
    category: "tragedy",
  },
  {
    questionText: "Which 21-year-old rapper was shot and killed in Hollywood Hills in late 2019?",
    correctAnswer: "Pop Smoke",
    options: ["Pop Smoke", "Juice WRLD", "Mac Miller", "Lil Peep"],
    artistName: "Pop Smoke",
    funFact: "Pop Smoke was killed during a home invasion in February 2020 — his posthumous album debuted at #1.",
    backgroundSongName: "Welcome to the Party",
    backgroundArtist: "Pop Smoke",
    difficulty: "medium",
    category: "tragedy",
  },
  {
    questionText: "Which 21-year-old rapper died from an accidental drug overdose at Chicago's Midway Airport in 2019?",
    correctAnswer: "Juice WRLD",
    options: ["Juice WRLD", "Lil Peep", "Mac Miller", "XXXTentacion"],
    artistName: "Juice WRLD",
    funFact: "He swallowed several Percocet pills before a police search to hide them, leading to his death.",
    backgroundSongName: "Lucid Dreams",
    backgroundArtist: "Juice WRLD",
    difficulty: "medium",
    category: "tragedy",
  },

  // ─── COMEBACKS & REUNIONS ─────────────────────────────
  {
    questionText: "Which 2025 Oasis tour reunion sold out in record time and became the music event of the year?",
    correctAnswer: "Oasis Live '25",
    options: ["Oasis Live '25", "Britpop Forever", "Wonderwall World Tour", "Definitely Maybe Reunion"],
    artistName: "Oasis",
    funFact: "Liam and Noel Gallagher reunited after 16 years of public feuding — fans waited 14+ hours in queues.",
    backgroundSongName: "Don't Look Back in Anger",
    backgroundArtist: "Oasis",
    difficulty: "easy",
    category: "comeback",
    gossipDate: "2025",
  },
  {
    questionText: "Which 70s rock band did Mick Fleetwood and Christine McVie reunite with in 2014 after 16 years?",
    correctAnswer: "Fleetwood Mac",
    options: ["Fleetwood Mac", "Eagles", "Led Zeppelin", "The Who"],
    artistName: "Fleetwood Mac",
    funFact: "Christine McVie returned for the 'On with the Show' tour, but sadly died in 2022.",
    backgroundSongName: "Don't Stop",
    backgroundArtist: "Fleetwood Mac",
    difficulty: "medium",
    category: "comeback",
  },
  {
    questionText: "Which 2007 reunion concert featured Led Zeppelin's first full performance in 19 years?",
    correctAnswer: "Ahmet Ertegun Tribute Concert",
    options: [
      "Ahmet Ertegun Tribute Concert",
      "Live Aid",
      "Live 8",
      "Glastonbury",
    ],
    artistName: "Led Zeppelin",
    funFact: "Jason Bonham played drums in place of his late father John Bonham.",
    backgroundSongName: "Stairway to Heaven",
    backgroundArtist: "Led Zeppelin",
    difficulty: "hard",
    category: "comeback",
  },
  {
    questionText: "Which iconic 90s grunge band did Dave Grohl found after Kurt Cobain's death?",
    correctAnswer: "Foo Fighters",
    options: ["Foo Fighters", "Pearl Jam", "Soundgarden", "Stone Temple Pilots"],
    artistName: "Foo Fighters",
    funFact: "Grohl played every instrument on the first Foo Fighters album in just one week.",
    backgroundSongName: "Everlong",
    backgroundArtist: "Foo Fighters",
    difficulty: "easy",
    category: "comeback",
  },

  // ─── WEDDINGS & RELATIONSHIPS ─────────────────────────
  {
    questionText: "Which pop star married NFL player Travis Kelce in 2024 — wait, no, they're not married. Which couple ARE engaged as of 2024?",
    correctAnswer: "They started dating in 2023 (not engaged)",
    options: [
      "They started dating in 2023 (not engaged)",
      "Justin Bieber & Selena Gomez",
      "Harry Styles & Olivia Wilde",
      "Camila Cabello & Shawn Mendes",
    ],
    artistName: "Taylor Swift",
    funFact: "Taylor Swift's relationship with Travis Kelce became one of the biggest pop culture stories of 2023-2024.",
    backgroundSongName: "Karma",
    backgroundArtist: "Taylor Swift",
    difficulty: "easy",
    category: "relationship",
    gossipDate: "2024",
  },
  {
    questionText: "Which singer married actor Brad Pitt in 2000 before their famous 2005 split?",
    correctAnswer: "Jennifer Aniston (actress, not singer)",
    options: [
      "Jennifer Aniston (actress, not singer)",
      "Madonna",
      "Britney Spears",
      "Mariah Carey",
    ],
    artistName: "Brad Pitt",
    funFact: "Brad left Jennifer Aniston for Angelina Jolie after meeting her on 'Mr. & Mrs. Smith'.",
    backgroundSongName: "Since U Been Gone",
    backgroundArtist: "Kelly Clarkson",
    difficulty: "hard",
    category: "relationship",
  },
  {
    questionText: "Which legendary singer married 8 different men, twice to the same one (Richard Burton)?",
    correctAnswer: "Elizabeth Taylor (actress, not singer)",
    options: [
      "Elizabeth Taylor (actress, not singer)",
      "Cher",
      "Tina Turner",
      "Diana Ross",
    ],
    artistName: "Elizabeth Taylor",
    funFact: "Liz famously said 'I don't pretend to be an ordinary housewife.' She married Richard Burton twice.",
    backgroundSongName: "Diamonds Are a Girl's Best Friend",
    backgroundArtist: "Marilyn Monroe",
    difficulty: "hard",
    category: "relationship",
  },

  // ─── DRUG & ALCOHOL ───────────────────────────────────
  {
    questionText: "Which Rolling Stones member underwent a famously full blood transfusion in the 1970s to clean out his heroin?",
    correctAnswer: "Keith Richards",
    options: ["Keith Richards", "Mick Jagger", "Brian Jones", "Charlie Watts"],
    artistName: "Keith Richards",
    funFact: "The blood transfusion story is mostly myth — Keith spread it himself to make people stop asking about drugs.",
    backgroundSongName: "Brown Sugar",
    backgroundArtist: "The Rolling Stones",
    difficulty: "hard",
    category: "drugs",
  },
  {
    questionText: "Which legendary Beatles producer publicly fired the band over their drug use — but did they leave him?",
    correctAnswer: "George Martin (he stayed with them)",
    options: [
      "George Martin (he stayed with them)",
      "Phil Spector",
      "Brian Epstein",
      "Allen Klein",
    ],
    artistName: "The Beatles",
    funFact: "George Martin produced almost every Beatles song until their breakup — drug use never separated them.",
    backgroundSongName: "Lucy in the Sky with Diamonds",
    backgroundArtist: "The Beatles",
    difficulty: "hard",
    category: "drugs",
  },

  // ─── TAYLOR SWIFT MASTERS ─────────────────────────────
  {
    questionText: "Why did Taylor Swift re-record her old albums starting in 2021?",
    correctAnswer: "To own the master recordings",
    options: [
      "To own the master recordings",
      "Because they sounded outdated",
      "For a Greatest Hits release",
      "As a publicity stunt",
    ],
    artistName: "Taylor Swift",
    funFact: "Scooter Braun bought Taylor's masters from Big Machine in 2019, prompting her re-recording project.",
    backgroundSongName: "Shake It Off",
    backgroundArtist: "Taylor Swift",
    difficulty: "easy",
    category: "drama",
  },
  {
    questionText: "Which feud started when Scooter Braun bought Big Machine Records and Taylor Swift's masters in 2019?",
    correctAnswer: "Taylor Swift vs. Scooter Braun",
    options: [
      "Taylor Swift vs. Scooter Braun",
      "Taylor Swift vs. Kanye West",
      "Taylor Swift vs. Katy Perry",
      "Taylor Swift vs. Calvin Harris",
    ],
    artistName: "Taylor Swift",
    funFact: "Taylor called the deal 'her worst case scenario' — Braun previously managed Kanye West.",
    backgroundSongName: "Look What You Made Me Do",
    backgroundArtist: "Taylor Swift",
    difficulty: "medium",
    category: "drama",
  },

  // ─── KANYE WEST DRAMA ─────────────────────────────────
  {
    questionText: "Which 2022 Kanye West controversy involved antisemitic tweets that lost him his Adidas deal?",
    correctAnswer: "His 'death con 3' tweet about Jewish people",
    options: [
      "His 'death con 3' tweet about Jewish people",
      "His Trump endorsement",
      "His White Lives Matter shirt",
      "His Yeezy lawsuits",
    ],
    artistName: "Kanye West",
    funFact: "Adidas terminated their billion-dollar Yeezy deal — Kanye lost his billionaire status overnight.",
    backgroundSongName: "Stronger",
    backgroundArtist: "Kanye West",
    difficulty: "medium",
    category: "scandal",
  },
  {
    questionText: "Which Kim Kardashian husband received the famous 'death con 3' diss in Drake's 'Family Matters' verse?",
    correctAnswer: "Kanye West (different Drake feud)",
    options: [
      "Kanye West (different Drake feud)",
      "Kris Humphries",
      "Damon Thomas",
      "Pete Davidson",
    ],
    artistName: "Kanye West",
    funFact: "Kim and Kanye divorced in 2022 — Kim then dated Pete Davidson, fueling Kanye's fury.",
    backgroundSongName: "Heartless",
    backgroundArtist: "Kanye West",
    difficulty: "hard",
    category: "drama",
  },

  // ─── BAND BREAKUPS ────────────────────────────────────
  {
    questionText: "Which member's departure caused The Beatles' famous 1970 breakup?",
    correctAnswer: "Paul McCartney (officially)",
    options: [
      "Paul McCartney (officially)",
      "John Lennon",
      "George Harrison",
      "Ringo Starr",
    ],
    artistName: "The Beatles",
    funFact: "Paul publicly announced the split in 1970, but John had already wanted out years earlier.",
    backgroundSongName: "Let It Be",
    backgroundArtist: "The Beatles",
    difficulty: "medium",
    category: "breakup",
  },
  {
    questionText: "Which member of Pink Floyd was famously fired due to mental health and creative differences in 1985?",
    correctAnswer: "Roger Waters",
    options: ["Roger Waters", "David Gilmour", "Nick Mason", "Richard Wright"],
    artistName: "Pink Floyd",
    funFact: "Waters didn't return for Pink Floyd's 2005 Live 8 reunion — the band's relationships remained tense.",
    backgroundSongName: "Comfortably Numb",
    backgroundArtist: "Pink Floyd",
    difficulty: "hard",
    category: "breakup",
  },
  {
    questionText: "Which Eagles member was fired from the band over a dispute that lasted decades?",
    correctAnswer: "Don Felder",
    options: ["Don Felder", "Glenn Frey", "Don Henley", "Joe Walsh"],
    artistName: "Eagles",
    funFact: "Don Felder co-wrote 'Hotel California' but was fired in 2001 — he later sued the band.",
    backgroundSongName: "Hotel California",
    backgroundArtist: "Eagles",
    difficulty: "hard",
    category: "breakup",
  },

  // ─── CHRIS BROWN / RIHANNA ────────────────────────────
  {
    questionText: "Which 2009 incident shocked the music world the night before the Grammys?",
    correctAnswer: "Chris Brown assaulted Rihanna",
    options: [
      "Chris Brown assaulted Rihanna",
      "Kanye crashed Adele's car",
      "Beyoncé walked off stage",
      "Eminem sued his mom",
    ],
    artistName: "Chris Brown",
    funFact: "Chris Brown pleaded guilty to felony assault and was sentenced to 5 years probation.",
    backgroundSongName: "Take a Bow",
    backgroundArtist: "Rihanna",
    difficulty: "medium",
    category: "scandal",
  },

  // ─── 2024-2025 GOSSIP ─────────────────────────────────
  {
    questionText: "Which artist's 2024 album 'The Tortured Poets Department' broke Spotify single-day streaming records?",
    correctAnswer: "Taylor Swift",
    options: ["Taylor Swift", "Beyoncé", "Olivia Rodrigo", "Billie Eilish"],
    artistName: "Taylor Swift",
    funFact: "TTPD got over 300 million streams in its first day — Taylor's biggest debut ever.",
    backgroundSongName: "Fortnight",
    backgroundArtist: "Taylor Swift",
    difficulty: "easy",
    category: "milestone",
    gossipDate: "2024",
  },
  {
    questionText: "Which 2024 country crossover hit by Beyoncé made her the first Black woman to top the Billboard country charts?",
    correctAnswer: "Texas Hold 'Em",
    options: ["Texas Hold 'Em", "II Most Wanted", "Daughter", "16 Carriages"],
    artistName: "Beyoncé",
    funFact: "'Cowboy Carter' became Beyoncé's eighth #1 album when it released in March 2024.",
    backgroundSongName: "Texas Hold 'Em",
    backgroundArtist: "Beyoncé",
    difficulty: "easy",
    category: "milestone",
    gossipDate: "2024",
  },
  {
    questionText: "Which Sabrina Carpenter song became 2024's surprise viral pop hit?",
    correctAnswer: "Espresso",
    options: ["Espresso", "Please Please Please", "Feather", "Nonsense"],
    artistName: "Sabrina Carpenter",
    funFact: "'Espresso' helped Sabrina Carpenter become one of the biggest pop stars of 2024.",
    backgroundSongName: "Espresso",
    backgroundArtist: "Sabrina Carpenter",
    difficulty: "easy",
    category: "viral",
    gossipDate: "2024",
  },
  {
    questionText: "Which Chappell Roan song made her 2024's breakout queer pop star?",
    correctAnswer: "Good Luck, Babe!",
    options: ["Good Luck, Babe!", "Pink Pony Club", "Hot To Go!", "Red Wine Supernova"],
    artistName: "Chappell Roan",
    funFact: "Chappell Roan went viral in 2024 thanks to her 'Pink Pony Club' aesthetic and powerful vocals.",
    backgroundSongName: "Good Luck, Babe!",
    backgroundArtist: "Chappell Roan",
    difficulty: "medium",
    category: "viral",
    gossipDate: "2024",
  },
  {
    questionText: "Which 2024 Brat Summer phenomenon was sparked by which artist?",
    correctAnswer: "Charli XCX",
    options: ["Charli XCX", "Doja Cat", "Tate McRae", "Olivia Rodrigo"],
    artistName: "Charli XCX",
    funFact: "Charli's 'Brat' album turned the lime green color into the defining aesthetic of 2024.",
    backgroundSongName: "Apple",
    backgroundArtist: "Charli XCX",
    difficulty: "easy",
    category: "viral",
    gossipDate: "2024",
  },
  {
    questionText: "Which veteran rocker famously announced retirement in 2025 after a Parkinson's diagnosis?",
    correctAnswer: "Ozzy Osbourne",
    options: ["Ozzy Osbourne", "Mick Jagger", "Paul McCartney", "Roger Waters"],
    artistName: "Ozzy Osbourne",
    funFact: "Ozzy's farewell concert with Black Sabbath in 2025 became one of metal's most emotional moments.",
    backgroundSongName: "Mama, I'm Coming Home",
    backgroundArtist: "Ozzy Osbourne",
    difficulty: "medium",
    category: "retirement",
    gossipDate: "2025",
  },

  // ─── COURT CASES ──────────────────────────────────────
  {
    questionText: "Which 2015 court case found Robin Thicke and Pharrell guilty of copying Marvin Gaye's 'Got to Give It Up'?",
    correctAnswer: "The 'Blurred Lines' lawsuit",
    options: [
      "The 'Blurred Lines' lawsuit",
      "Stairway to Heaven case",
      "Dark Horse case",
      "Stay With Me case",
    ],
    artistName: "Robin Thicke",
    funFact: "Marvin Gaye's family was awarded $7.4 million — later reduced to $5.3 million on appeal.",
    backgroundSongName: "Blurred Lines",
    backgroundArtist: "Robin Thicke",
    difficulty: "medium",
    category: "lawsuit",
  },
  {
    questionText: "Which 2020 Olivia Rodrigo song was sued for similarities to Paramore's 'Misery Business'?",
    correctAnswer: "Good 4 U",
    options: ["Good 4 U", "Drivers License", "Brutal", "Deja Vu"],
    artistName: "Olivia Rodrigo",
    funFact: "Olivia gave songwriting credits to Paramore retroactively to settle the lawsuit.",
    backgroundSongName: "Good 4 U",
    backgroundArtist: "Olivia Rodrigo",
    difficulty: "medium",
    category: "lawsuit",
  },

  // ─── FAKE/REAL NAMES ──────────────────────────────────
  {
    questionText: "What is Lady Gaga's real name?",
    correctAnswer: "Stefani Joanne Angelina Germanotta",
    options: [
      "Stefani Joanne Angelina Germanotta",
      "Stephanie Maria Germano",
      "Gabriella Stefani Germano",
      "Stella Germani",
    ],
    artistName: "Lady Gaga",
    funFact: "Her stage name comes from Queen's 'Radio Ga Ga' — her producer kept calling her that.",
    backgroundSongName: "Bad Romance",
    backgroundArtist: "Lady Gaga",
    difficulty: "medium",
    category: "trivia",
  },
  {
    questionText: "What is Bruno Mars' real name?",
    correctAnswer: "Peter Gene Hernandez",
    options: ["Peter Gene Hernandez", "Bruno Hernandez", "Peter Mars", "Pedro Hernandez"],
    artistName: "Bruno Mars",
    funFact: "His father nicknamed him 'Bruno' after wrestler Bruno Sammartino as a baby.",
    backgroundSongName: "Uptown Funk",
    backgroundArtist: "Bruno Mars",
    difficulty: "medium",
    category: "trivia",
  },
  {
    questionText: "What is The Weeknd's real name?",
    correctAnswer: "Abel Tesfaye",
    options: ["Abel Tesfaye", "Aaron Tesfaye", "Abdul Hassan", "Adam Sefali"],
    artistName: "The Weeknd",
    funFact: "He dropped the 'e' in 'Weekend' to avoid trademark issues with a Canadian band of the same name.",
    backgroundSongName: "Blinding Lights",
    backgroundArtist: "The Weeknd",
    difficulty: "medium",
    category: "trivia",
  },
];

async function main() {
  const existing = JSON.parse(readFileSync(PATH, 'utf-8'));
  const existingTexts = new Set(existing.map(q => q.questionText));

  let added = 0;
  for (const q of QUESTIONS) {
    if (existingTexts.has(q.questionText)) continue;
    existing.push({
      id: crypto.randomBytes(4).toString('hex'),
      questionType: 'gossip',
      ...q,
      validated: true,
      timesUsed: 0,
      createdAt: new Date().toISOString(),
      source: 'opus-curated',
    });
    added++;
  }

  writeFileSync(PATH, JSON.stringify(existing, null, 2));
  console.log(`✅ Added ${added} gossip questions. Total: ${existing.length}`);

  // Category distribution
  const cats = {};
  for (const q of existing) {
    const c = q.category || 'uncategorized';
    cats[c] = (cats[c] || 0) + 1;
  }
  console.log('\nCategory distribution:');
  for (const [c, n] of Object.entries(cats).sort((a, b) => b[1] - a[1])) {
    console.log(`  ${c}: ${n}`);
  }
}

main().catch(err => { console.error('FATAL:', err); process.exit(1); });
